version: '3.4'

services:
  demo:
    image: mct-researchproject-karelbousson
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
