version: '3.4'

services:
  demo:
    image: ghcr.io/boussonkarel/mct-researchproject:vr
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
